api_key: APIfdPdDzaf5N2B
api_secret: s7fkuYnWBRSYki4WXwrDJiSvBNgafwZ3ffWpd47IKDRA
ws_url: ws://127.0.0.1:7880
logging:
  level: debug
redis:
  address: localhost:6379
sip_port: 5062
rtp_audio_port: 10000-20000
rtp_video_port: 30000-40000
use_external_ip: false
use_stun: true
stun_url: 'stun:127.0.0.1:3478'
codecs:
  G722/8000: false